environment: prod
project_name: ATHENA
jewel_user: pallaviarora
#jewel_bridge_token: 3c746c90-69da-4365-b530-ea1cdfb37ae21716282288009
#enter_point: https://betaapi.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
#prod token
jewel_bridge_token: fc815b69-105d-43d9-b5d5-0c9b0e65384b1709529202843
enter_point: https://apis.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
report_name: Athena_Report
email_report: N
jewel_screen_shots: Y/N
#tags: '@cucumber_tag'
glue_code: com.gemini.athenaAPI.stepDefinition.APIStepDefinition
#glue_code: com.gemini.athena.stepdefinitions
beta:
  browser_name: chrome
  launch_url: https://athena-dev.geminisolutions.com
#  launch_url: http://localhost:4200/athena
  browser_timeout: 100
  authenticate_url : https://devapi.geminisolutions.com/gemassessment/authenticate
  getAllUsers : https://devapi.geminisolutions.com/gemassessment/api/users
  saveUser : https://devapi.geminisolutions.com/gemassessment/api/registerUser
  findUser : https://devapi.geminisolutions.com/gemassessment/api/findUser/saloni.nagpal@geminisolutions.com
  findAllUser : https://devapi.geminisolutions.com/gemassessment/api/findActiveusers
  getQuestionTypes : https://devapi.geminisolutions.com/gemassessment/api/getQuestionTypes
  getAllQuestions : http://devapi.geminisolutions.com/gemassessment/api/getQuestions
  getQuestionById : http://devapi.geminisolutions.com/gemassessment/api/getQuestion/19
  forgotPassword : http://devapi.geminisolutions.com/gemassessment/user/forgotPassword
  getTestMaster : https://devapi.geminisolutions.com/gemassessment/api/getTest
  getTestById : https://devapi.geminisolutions.com/gemassessment/api/getTest/17
  addCandidateTest : https://devapi.geminisolutions.com/gemassessment/api/addCandidateTest
  getRandomQuestions : https://devapi.geminisolutions.com/gemassessment/api/getRandomQuestions?questionCount=5&sectionTypeId=1&difficulty=Medium&questionTypeId=2&tags=test
  paginatedGetTest : https://devapi.geminisolutions.com/gemassessment/api/getAllPaginatedTests?testTag=mat&pageNumber=0&pageSize=9
  getAllCandidatesByTestId : https://devapi.geminisolutions.com/gemassessment/api/getAllCandidates/1
  getAllActiveCandidate : https://devapi.geminisolutions.com/gemassessment/api/getAllActiveCandidateUsers?pageIndex=0&pageSize=2
  getActiveTestAndQuestionCount : https://devapi.geminisolutions.com/gemassessment/api/getActiveTestQuestionCountAndSectionTypeCount
  removeCandidateFromTest : https://devapi.geminisolutions.com/gemassessment/api/removeCandidateFromTest/12/1
  getCandidateAnswer : https://devapi.geminisolutions.com/gemassessment/api/getAllAnswer/20

