environment: prod
project_name: ATHENA
jewel_user: pallaviarora
#jewel_bridge_token: 3c746c90-69da-4365-b530-ea1cdfb37ae21716282288009
#enter_point: https://betaapi.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
#prod token
jewel_bridge_token: 9dbeea5c-65e3-4e2b-b115-91b731cbf3991722920219348
enter_point: https://apis.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
report_name: Athena_Report
email_report: Y
email_to: pallavi.arora@geminisolutions.com
email_cc: abhishek.gautam@geminisolutions.com
jewel_screen_shots: Y/N
#tags: '@cucumber_tag'
glue_code: com.gemini.athenaAPI.stepDefinition.APIStepDefinition
#glue_code: com.gemini.athena.stepdefinitions
#browser_name: chrome
#launch_url: https://athena-dev.geminisolutions.com
#launch_url: http://localhost:4200/athena

prod:
  browser_name: chrome
  launch_url: https://athena-dev.geminisolutions.com
#  launch_url: http://localhost:4200/athena
  browser_timeout: 100
  authenticate_url : https://devapi.geminisolutions.com/gemassessment/authenticate
  getAllUsers : https://devapi.geminisolutions.com/gemassessment/api/users
  saveUser : https://devapi.geminisolutions.com/gemassessment/api/registerUser
  findUser : https://devapi.geminisolutions.com/gemassessment/api/findUser/pallavi.arora@geminisolutions.com
  findAllUser : https://devapi.geminisolutions.com/gemassessment/api/findActiveusers
  getQuestionTypes : https://devapi.geminisolutions.com/gemassessment/api/getQuestionTypes
  getAllQuestions : http://devapi.geminisolutions.com/gemassessment/api/getQuestions
  getQuestionById : http://devapi.geminisolutions.com/gemassessment/api/getQuestion/19
  forgotPassword : http://devapi.geminisolutions.com/gemassessment/user/forgotPassword
  getTestMaster : https://devapi.geminisolutions.com/gemassessment/api/getTest
  getTestById : https://devapi.geminisolutions.com/gemassessment/api/getTest/17
  addCandidateTest : https://devapi.geminisolutions.com/gemassessment/api/addCandidateTest
  getRandomQuestions : https://devapi.geminisolutions.com/gemassessment/api/getRandomQuestions?questionCount=5&sectionTypeId=1&difficulty=Medium&questionTypeId=2&tags=test
  paginatedGetTest : https://devapi.geminisolutions.com/gemassessment/api/getAllPaginatedTests?testTag=mat&pageNumber=0&pageSize=9
  getAllCandidatesByTestId : https://devapi.geminisolutions.com/gemassessment/api/getAllCandidates/1
  getAllActiveCandidate : https://devapi.geminisolutions.com/gemassessment/api/getAllActiveCandidateUsers?pageIndex=0&pageSize=2
  getActiveTestAndQuestionCount : https://devapi.geminisolutions.com/gemassessment/api/getActiveTestQuestionCountAndSectionTypeCount
  removeCandidateFromTest : https://devapi.geminisolutions.com/gemassessment/api/removeCandidateFromTest/12/1
  getCandidateAnswer : https://devapi.geminisolutions.com/gemassessment/api/getAllAnswer/20
  generateReport: https://devapi.geminisolutions.com/gemassessment/api/generateReport/1
  getAllTests: https://devapi.geminisolutions.com/gemassessment/api/getAllAssignedTests/10
  getAllUsersPaginated: https://devapi.geminisolutions.com/gemassessment/api/allUsersPaginated?pageIndex=0&pageSize=50&roles=2&roles=3&roles=4&roles=1001
  clearAnswer: https://devapi.geminisolutions.com/gemassessment/api/clearAnswer/
  addTest: https://devapi.geminisolution.com/gemassessment/api/addTest
  getUserById: https://devapi.geminisolutions.com/gemassessment/api/user/1
  addSection: https://devapi.geminisolutions.com/gemassessment/api/addSection
  getSection: https://devapi.geminisolutions.com/gemassessment/api/sections
  getActiveQuestionCount: https://devapi.geminisolutions.com/gemassessment/api/getActiveQuestionCount/1
  getUser: https://devapi.geminisolutions.com/gemassessment/api/getUser
  getActiveTest: https://devapi.geminisolutions.com/gemassessment/api/getActiveTest?isInternalTest=false
  deleteQuestion: https://devapi.geminisolutions.com/gemassessment/api/deleteQuestion/1341
  getTestAssociatedQuestion: https://devapi.geminisolutions.com/gemassessment/api/getTestAssociatedQuestion/2
  deleteOption: https://devapi.geminisolutions.com/gemassessment/api/deleteOption/2
  removeQuestionFromTest: https://devapi.geminisolutions.com/gemassessment/api/removeQuestionFromTest/3
  deleteSectionType: https://devapi.geminisolutions.com/gemassessment/api/deleteSectionType/101
  getTestAssociatedSections: https://devapi.geminisolutions.com/gemassessment/api/getTestAssociatedSections/2
  getAllCampus: https://devapi.geminisolutions.com/gemassessment/api/getAllCampus
  getAllActiveCampus: https://devapi.geminisolutions.com/gemassessment/api/getAllActiveCampus
  getRole: https://devapi.geminisolutions.com/gemassessment/api/getRole/7
  getRoles: https://devapi.geminisolutions.com/gemassessment/api/getRoles
  getAllPermissions: https://devapi.geminisolutions.com/gemassessment/api/getAllPermissions
  getPermissionByCode: https://devapi.geminisolutions.com/gemassessment/api/getPermissionByCode/CREATE_EDIT_TEST
  getCampusById: https://devapi.geminisolutions.com/gemassessment/api/getCampusById/2
  getCampusReportsByCampusId: https://devapi.geminisolutions.com/gemassessment/api/getCampusReportsByCampusId/3
  getComprehensionById: https://devapi.geminisolutions.com/gemassessment/api/getComprehensionById/1
  getAllComprehensions: https://devapi.geminisolutions.com/gemassessment/api/getAllComprehensions
  getAllComprehensionAssocQuestions: https://devapi.geminisolutions.com/gemassessment/api/getAllComprehensionAssocQuestions
  getAllMovieClips: https://devapi.geminisolutions.com/gemassessment/api/getAllMovieClips
  getAllMovieAssocQuestions: https://devapi.geminisolutions.com/gemassessment/api/getAllMovieAssocQuestions
  getMovieById: https://devapi.geminisolutions.com/gemassessment/api/getMovieById/1
  getMovieByName: https://devapi.geminisolutions.com/gemassessment/api/getMovieByName?movieName=RCQSBDI
  getMovieAssocQuestionsById: https://devapi.geminisolutions.com/gemassessment/api/getMovieAssocQuestionsById/1
  getAllActiveTest: https://devapi.geminisolutions.com/gemassessment/api/getAllActiveTest
  deleteMovie: https://devapi.geminisolutions.com/gemassessment/api/deleteMovie/100
  getCampusPerformanceReport: https://devapi.geminisolutions.com/gemassessment/api/getCampusPerformanceReport?year=2024&campusMasterId=1
  getAllPaginatedCandidates: https://devapi.geminisolutions.com/gemassessment/api/getAllPaginatedCandidates/26?invigilatorEmail="gargp97@gmail.com"
  addQuestions: https://devapi.geminisolutions.com/gemassessment/api/addQuestions
  addCandidateAnswer: https://devapi.geminisolutions.com/gemassessment/api/addAnswer
  saveCampusDetails: https://devapi.geminisolutions.com/gemassessment/api/saveCampusDetails
  addRole: https://devapi.geminisolutions.com/gemassessment/api/addRole
  updateUserPasswordManually: https://devapi.geminisolutions.com/gemassessment/user/updateUserPasswordManually
  saveComprehensionDetails: https://devapi.geminisolutions.com/gemassessment/api/saveComprehensionDetails
  reattemptTest: https://devapi.geminisolutions.com/gemassessment/api/reattemptTest
  sendEmail: https://devapi.geminisolutions.com/gemassessment/api/sendEmail
  getAllPaginatedQuestions: https://devapi.geminisolutions.com/gemassessment/api/getAllPaginatedQuestions
  addMovieQuestion: https://devapi.geminisolutions.com/gemassessment/api/addQuestions
  assignAllUsersToTest: https://devapi.geminisolutions.com/gemassessment/api/assignAllUsersToTest
  removeMovieQuestionAssoc: https://devapi.geminisolutions.com/gemassessment/api/removeMovieQuestionAssoc
  removeComprehensionQuestionAssoc: https://devapi.geminisolutions.com/gemassessment/api/removeComprehensionQuestionAssoc
  updateTestStatus: https://devapi.geminisolutions.com/gemassessment/api/updateTestStatus/101/true
  updateUser: https://devapi.geminisolutions.com/gemassessment/api/updateUser
  getTestInfoByTag: https://devapi.geminisolutions.com/gemassessment/api/getTestInfoByTag/nnnnnnnnn
  updateMarks: https://devapi.geminisolutions.com/gemassessment/api/updateMarks
  updatePassword: https://devapi.geminisolutions.com/gemassessment/api/updatePassword
  updateQuestion: https://devapi.geminisolutions.com/gemassessment/api/updateQuestion
  getComprehensionAssocQuestions: https://devapi.geminisolutions.com/gemassessment/api/getComprehensionAssocQuestions/1
  assignRandomEvaluators: https://devapi.geminisolutions.com/gemassessment/api/assignRandomEvaluators/26?emailList=abc@gmail.com